name: Daily Update
on: workflow_dispatch

env:
  NODE_VERSION: 21
  PNPM_VERSION: 8

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v3
        name: Setup pnpm
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install

      - name: Configure mailer
        run: sudo apt install sendmail

      - name: Run checks
        run: pnpm start
